name: lemmy04-signal-cli # you probably want to 'snapcraft register <name>'
version: '0.9.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A command line client for signal # 79 char long summary
description: |
  signal-cli is a commandline client for the Signal messenger service.

##architectures:
##  - build-on: amd64

confinement: strict # use 'strict' once you have the right plugs and slots
grade: edge
base: core20

parts:
  signal-cli:
    plugin: dump
    source: https://github.com/AsamK/signal-cli/releases/download/v0.9.1/signal-cli-0.9.1.tar.gz
    build-packages: 
    - openjdk-11-jre-headless
    - ca-certificates
    - ca-certificates-java
    - libunixsocket-java
    - qrencode
    stage-packages: 
    - openjdk-11-jre-headless
    - libunixsocket-java
    - qrencode

apps:
  signal-cli:
    command: bin/signal-cli
    plugs: [network, home]
    environment:
      JAVA_HOME: "${SNAP}/usr/lib/jvm/java-11-openjdk-${SNAP_ARCH}"

  qrencode:
    command: usr/bin/qrencode
